name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./Wedding.Api --file Wedding.Api/Docker/Dockerfile --tag thibaultlesuisse/valentine-philippe:latest
