name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./Wedding.Api
        file: ./Wedding.Api/Docker/Dockerfile
        push: true
        tags: thibaultlesuisse/valentinephilippeapi:latest
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./front
        file: ./front/docker/Dockerfile
        push: true
        tags: thibaultlesuisse/valentinephilippe:latest
